language: php

sudo: false

dist: trusty

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install: cp .env.example .env

install: travis_retry composer install --no-interaction --no-scripts --prefer-source

script: vendor/bin/phpunit
